"""Canonical stratified splits — single source of truth for all modeling (modeling pipeline).

All modeling tasks use the SAME split, generated by load_feature_splits(). This
ensures that baseline benchmarking, champion selection, calibration, stability
analysis, and SHAP explainability all operate on identical train/val/test partitions.

Split proportions: 70% train / 15% validation / 15% test (stratified on churn_binary).

Key invariants:
  - FE threshold fit (monthly_spend_q75, lifetime_arpu_q75) on TRAIN ONLY.
    These are percentile-based thresholds used by feature engineering
    (e.g., spend_cap, arpu_cap). Fitting them on train only prevents
    val/test leakage.
  - Calibrator is fit on VALIDATION P_RAW ONLY (not in this module — documented
    in meta for governance traceability).
  - The test split is NEVER used for ANY model fit, threshold selection, or
    calibration decision. It is purely evaluative.
  - A backward-compatible tuple return exists via load_feature_splits_legacy().

Pipeline position: consumed by every other modeling module (baselines, champion,
  stability, explainability, etc.).
Workflow stage: training (split creation is the first step).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from feature_engineering.builders import (
    build_features,
    fit_lifetime_arpu_q75,
    fit_monthly_spend_q75,
    get_model_feature_columns,
)
from modeling.config import (
    CLEANED_PATH,
    RANDOM_STATE,
    TEST_SIZE,
    TRAIN_SIZE,
    VAL_SIZE,
)


@dataclass
class SplitBundle:
    """Container for the canonical train/validation/test split with metadata.

    Attributes:
        meta: Dict with split dimensions, churn rates, FE schema versions, and policies.
        X_train: Training feature matrix (numpy float64).
        y_train: Training labels (numpy int8).
        X_val: Validation feature matrix.
        y_val: Validation labels.
        X_test: Test feature matrix.
        y_test: Test labels.
        train_df: Full training DataFrame (feature-engineered).
        val_df: Full validation DataFrame.
        test_df: Full test DataFrame.
        feature_columns: List of feature column names (from get_model_feature_columns()).
        monthly_spend_q75: 75th percentile of monthly spend, fit on TRAIN only.
        lifetime_arpu_q75: 75th percentile of lifetime ARPU, fit on TRAIN only.
    """

    meta: dict[str, Any]
    X_train: np.ndarray
    y_train: np.ndarray
    X_val: np.ndarray
    y_val: np.ndarray
    X_test: np.ndarray
    y_test: np.ndarray
    train_df: pd.DataFrame
    val_df: pd.DataFrame
    test_df: pd.DataFrame
    feature_columns: list[str]
    monthly_spend_q75: float
    lifetime_arpu_q75: float


def create_stratified_splits(
    df: pd.DataFrame | None = None,
    *,
    cleaned_path: str | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return stratified index arrays for train, validation, and test splits.

    Uses two-stage train_test_split:
      1. Split 70/30 (train+val vs test) stratified on churn_binary.
      2. Split the train+val pool into train (70/85) and val (15/85) stratified.

    Final proportions: 70% train / 15% val / 15% test.

    Args:
        df: DataFrame with 'churn_binary' column. If None, loaded from cleaned_path.
        cleaned_path: Path to cleaned parquet. Ignored if df is provided.
            Defaults to config.CLEANED_PATH.

    Returns:
        Tuple of (train_indices, val_indices, test_indices) as numpy int arrays.

    Side effects: Reads parquet from disk if df is None.
    """
    if df is None:
        path = cleaned_path or str(CLEANED_PATH)
        df = pd.read_parquet(path)

    y = df["churn_binary"].values
    idx_all = np.arange(len(df))

    idx_trainval, idx_test = train_test_split(
        idx_all,
        test_size=TEST_SIZE,
        stratify=y,
        random_state=RANDOM_STATE,
    )
    val_ratio = VAL_SIZE / (1.0 - TEST_SIZE)
    idx_train, idx_val = train_test_split(
        idx_trainval,
        test_size=val_ratio,
        stratify=y[idx_trainval],
        random_state=RANDOM_STATE,
    )
    return idx_train, idx_val, idx_test
    if df is None:
        path = cleaned_path or str(CLEANED_PATH)
        df = pd.read_parquet(path)

    y = df["churn_binary"].values
    idx_all = np.arange(len(df))

    idx_trainval, idx_test = train_test_split(
        idx_all,
        test_size=TEST_SIZE,
        stratify=y,
        random_state=RANDOM_STATE,
    )
    val_ratio = VAL_SIZE / (1.0 - TEST_SIZE)
    idx_train, idx_val = train_test_split(
        idx_trainval,
        test_size=val_ratio,
        stratify=y[idx_trainval],
        random_state=RANDOM_STATE,
    )
    return idx_train, idx_val, idx_test


def load_feature_splits(
    df: pd.DataFrame | None = None,
    *,
    return_frames: bool = True,
) -> SplitBundle | tuple:
    """Load cleaned data, create stratified splits, fit train-only FE thresholds, build feature matrices.

    Workflow:
      1. Read cleaned parquet (or accept provided df).
      2. Create stratified splits via create_stratified_splits().
      3. Fit monthly_spend_q75 and lifetime_arpu_q75 on TRAIN ONLY.
      4. Build features for all three splits using train-fitted thresholds.
      5. Extract feature columns, convert to numpy arrays.
      6. Return as SplitBundle (or legacy tuple).

    Why FE thresholds are fit on train only:
        monthly_spend_q75 and lifetime_arpu_q75 are used for spend capping and
        ratio features. Fitting them on the full dataset would leak information
        from the val/test distributions into the training process. The thresholds
        are trained on train and applied to all splits.

    This is the ONLY function that should be used for modeling train/val/test
    access. All modules (baselines, champion, stability, explainability) must
    go through this single entry point.

    Args:
        df: Optional pre-loaded cleaned DataFrame. If None, loaded from CLEANED_PATH.
        return_frames: If True (default), return a SplitBundle with full DataFrames.
            If False, return a tuple (meta, X_train, y_train, X_val, y_val, X_test, y_test)
            for backward compatibility with minimal memory overhead.

    Returns:
        SplitBundle if return_frames=True, else a 7-element tuple.
    """
    if df is None:
        df = pd.read_parquet(CLEANED_PATH)

    idx_train, idx_val, idx_test = create_stratified_splits(df)

    train_raw = df.iloc[idx_train].reset_index(drop=True)
    val_raw = df.iloc[idx_val].reset_index(drop=True)
    test_raw = df.iloc[idx_test].reset_index(drop=True)

    q75_monthly = fit_monthly_spend_q75(train_raw)
    q75_arpu = fit_lifetime_arpu_q75(train_raw)

    train_fe = build_features(train_raw, monthly_spend_q75=q75_monthly, lifetime_arpu_q75=q75_arpu)
    val_fe = build_features(val_raw, monthly_spend_q75=q75_monthly, lifetime_arpu_q75=q75_arpu)
    test_fe = build_features(test_raw, monthly_spend_q75=q75_monthly, lifetime_arpu_q75=q75_arpu)

    cols = get_model_feature_columns()
    meta: dict[str, Any] = {
        "n_train": len(train_fe),
        "n_val": len(val_fe),
        "n_test": len(test_fe),
        "n_total": len(df),
        "churn_rate_train": float(train_fe["churn_binary"].mean()),
        "churn_rate_val": float(val_fe["churn_binary"].mean()),
        "churn_rate_test": float(test_fe["churn_binary"].mean()),
        "monthly_spend_q75_train": q75_monthly,
        "lifetime_arpu_q75_train": q75_arpu,
        "feature_columns": cols,
        "n_features": len(cols),
        "feature_engineering_schema": "task4-v2",
        "split_ratio": f"{TRAIN_SIZE:.0%} / {VAL_SIZE:.0%} / {TEST_SIZE:.0%} stratified",
        "random_state": RANDOM_STATE,
        "threshold_fit_policy": "monthly_spend_q75 and lifetime_arpu_q75 fit on train only",
        "calibration_fit_policy": "calibrator fit on validation p_raw only (not in this module)",
    }

    bundle = SplitBundle(
        meta=meta,
        X_train=train_fe[cols].values.astype(np.float64),
        y_train=train_fe["churn_binary"].values.astype(np.int8),
        X_val=val_fe[cols].values.astype(np.float64),
        y_val=val_fe["churn_binary"].values.astype(np.int8),
        X_test=test_fe[cols].values.astype(np.float64),
        y_test=test_fe["churn_binary"].values.astype(np.int8),
        train_df=train_fe if return_frames else pd.DataFrame(),
        val_df=val_fe if return_frames else pd.DataFrame(),
        test_df=test_fe if return_frames else pd.DataFrame(),
        feature_columns=cols,
        monthly_spend_q75=q75_monthly,
        lifetime_arpu_q75=q75_arpu,
    )

    if not return_frames:
        return (
            meta,
            bundle.X_train,
            bundle.y_train,
            bundle.X_val,
            bundle.y_val,
            bundle.X_test,
            bundle.y_test,
        )
    return bundle


# Backward-compatible tuple return for legacy callers.
def load_feature_splits_legacy() -> tuple:
    """Backward-compatible alias returning a flat tuple instead of a SplitBundle.

    Why this alias exists:
        Earlier versions of the codebase returned a 7-element tuple from
        load_feature_splits. When we migrated to a SplitBundle dataclass, this
        alias was retained to avoid breaking callers that unpack the tuple
        (meta, X_train, y_train, X_val, y_val, X_test, y_test).

    Returns:
        7-element tuple: (meta, X_train, y_train, X_val, y_val, X_test, y_test).
    """
    b = load_feature_splits()
    return (
        b.meta,
        b.X_train,
        b.y_train,
        b.X_val,
        b.y_val,
        b.X_test,
        b.y_test,
    )
