"""
Dashboard KPI and chart schemas for the executive summary view.

Pipeline position:
  Aggregates recommendation and prediction data into business-level KPIs and
  distribution charts. Consumed by the CRM dashboard frontend for the top-level
  overview page.

Workflow stage:
  GET /api/v1/dashboard/kpis -> KPIResponse
  GET /api/v1/dashboard/charts -> ChartsResponse
"""

from pydantic import BaseModel


class KPIResponse(BaseModel):
    """
    Top-level key performance indicators for the churn management dashboard.

    Includes:
      - Volume counts (total subscribers, actions by priority, high-risk, etc.)
      - Risk metrics (actual churn rate, average predicted churn, raw score)
      - Operational flags (digital-only, escalation-required, human-touch counts)
      - Governance status (compatibility_status) for artifact health at a glance
      - executive_summary: A natural-language headline generated by the dashboard service
    """

    total_subscribers: int
    actual_churn_rate: float
    avg_predicted_churn: float
    avg_raw_churn_score: float
    p1_action_count: int
    p2_action_count: int
    p3_action_count: int
    high_risk_count: int
    digital_only_count: int
    escalation_required_count: int
    human_touch_count: int
    fallback_rule_count: int
    compatibility_status: str
    executive_summary: str


class ChartSeries(BaseModel):
    """
    A single data point in a distribution chart.

    name: The bucket/category label (e.g., 'Very High', 'P1', 'postpaid').
    value: The numeric value (count, mean risk, etc.).
    """

    name: str
    value: float


class ChartsResponse(BaseModel):
    """
    Set of distribution charts for the dashboard.

    Each field is a list of ChartSeries representing the distribution of
    subscribers across key dimensions:
      - risk_distribution: By risk tier (Very High, High, Medium, Low).
      - campaign_priority_distribution: By P1/P2/P3 priority.
      - rule_distribution: By recommendation rule ID.
      - churn_by_sim_type: By SIM card type (postpaid/prepaid).
      - ecosystem_segment_distribution: By ecosystem segment.
      - crm_queue_distribution: By CRM queue assignment.
    """

    risk_distribution: list[ChartSeries]
    campaign_priority_distribution: list[ChartSeries]
    rule_distribution: list[ChartSeries]
    churn_by_sim_type: list[ChartSeries]
    ecosystem_segment_distribution: list[ChartSeries]
    crm_queue_distribution: list[ChartSeries]
