"""
SHAP explanation endpoint — per-subscriber model explainability.

Pipeline position:
  Retrieves stored SHAP explanations generated by the batch pipeline. SHAP data
  provides narrative context for CRM agents but never drives action selection.

Workflow stage:
  GET /api/v1/shap/{subscriber_id} -> ShapResponse

Security:
  Requires authentication via CurrentUser dependency.
"""

import json

from fastapi import APIRouter, HTTPException
from sqlalchemy import select

from app.core.deps import CurrentUser, DbSession
from app.models.shap_explanation import ShapExplanation
from app.schemas.shap import ShapDriver, ShapResponse

router = APIRouter()


@router.get("/{subscriber_id}", response_model=ShapResponse)
async def get_shap(subscriber_id: int, db: DbSession, _user: CurrentUser) -> ShapResponse:
    """
    Retrieve the SHAP explanation for a specific subscriber.

    Returns the top positive/negative drivers with SHAP values, business labels,
    effect direction, and a natural-language narrative summary. The response
    includes a static policy field reinforcing that SHAP is narrative-only.

    Args:
        subscriber_id: Subscriber ID to look up.
        db: Database session (injected dependency).
        _user: Authenticated user (enforced by auth dependency).

    Returns:
        ShapResponse with driver details and narrative.

    Raises:
        HTTPException 404: If no SHAP explanation exists for this subscriber.
    """
    result = await db.execute(
        select(ShapExplanation).where(ShapExplanation.subscriber_id == subscriber_id)
    )
    row = result.scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="SHAP explanation not found")
    pos = json.loads(row.positive_drivers_json)
    neg = json.loads(row.negative_drivers_json)
    return ShapResponse(
        subscriber_id=subscriber_id,
        positive_drivers=[ShapDriver(**d) for d in pos],
        negative_drivers=[ShapDriver(**d) for d in neg],
        narrative=row.narrative or "",
        shap_top_driver=row.shap_top_driver,
        shap_risk_up_drivers=row.shap_risk_up_drivers,
        shap_risk_down_drivers=row.shap_risk_down_drivers,
    )
